### ISSUE TITLE
not correct distribution

### ISSUE THREAD

**Issue by aflahu** [lukeed/wrr#1]
i've tried but not correct distribution

can u fix this?

**Comment by lukeed** [comment]
Hi, can you please clarify what you mean? I downloaded this & it all looks correct.
Thanks

**Comment by aflahu** [comment]
try this [repl.it](https://repl.it/repls/ImperfectNecessaryVariable#index.js)
found [ '127.0.0.1', '127.0.0.3', '127.0.0.2', '127.0.0.2', '127.0.0.2' ]

**Comment by lukeed** [comment]
It is correct. You cannot see anything with only 5 occurrences. It's a weighted distribution, not a round robin.

Increased to 1000 tests: https://repl.it/repls/PapayawhipSpottedInformationtechnology

You'll see something like this:

```js
{ '127.0.0.1': 210, '127.0.0.2': 394, '127.0.0.3': 396 }
```

As you can see, the `127.0.0.1` occurs about half as often as the other two (2:1).
